# Generated by Django 5.2 on 2025-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("result", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
