apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: scw-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: scw-app:latest
        imagePullPolicy: Never
        command: ["celery", "-A", "task_processor", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: django-config
        - secretRef:
            name: django-secrets
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"